<?php
declare(strict_types=1);

namespace Themis;

require_once __DIR__ . '/StrictErrorHandler.php';
require_once __DIR__ . '/Autoloader.php';

use Throwable;
use Themis\Combat\CombatService;
use Themis\System\DatabaseOperator;

header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
header('Pragma: no-cache');

if (session_status() !== PHP_SESSION_ACTIVE) {
	if (!session_start()) {
		http_response_code(500);
		echo json_encode(['ok' => false, 'error' => 'Session start failed']);
		exit;
	}
}

function combat_respond(int $status, array $payload): void
{
	http_response_code($status);
	echo json_encode($payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
	exit;
}

function combat_current_player_uuid(): string
{
	if (!isset($_SESSION['player']) || !is_array($_SESSION['player'])) {
		return '';
	}
	return trim((string)($_SESSION['player']['player_uuid'] ?? ''));
}

function combat_get_json_body(): array
{
	$raw = file_get_contents('php://input');
	if (!is_string($raw) || trim($raw) === '') {
		return [];
	}
	$decoded = json_decode($raw, true);
	return is_array($decoded) ? $decoded : [];
}

function combat_is_test_mode(array $body): bool
{
	$flag = (string)($_GET['test_mode'] ?? $_POST['test_mode'] ?? ($body['test_mode'] ?? ''));
	return trim($flag) === '1';
}

function combat_normalize_uuid(string $value): string
{
	$uuid = strtolower(trim($value));
	if ($uuid === '') {
		return '';
	}
	if (!preg_match('/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/', $uuid)) {
		return '';
	}
	return $uuid;
}

function combat_get_test_actor_uuid(array $body): ?string
{
	if (!combat_is_test_mode($body)) {
		return null;
	}
	$raw = (string)($_GET['test_actor_uuid'] ?? $_POST['test_actor_uuid'] ?? ($body['test_actor_uuid'] ?? ''));
	$uuid = combat_normalize_uuid($raw);
	return $uuid !== '' ? $uuid : null;
}

function combat_uuid_v4(): string
{
	$bytes = random_bytes(16);
	$bytes[6] = chr((ord($bytes[6]) & 0x0f) | 0x40);
	$bytes[8] = chr((ord($bytes[8]) & 0x3f) | 0x80);
	$hex = bin2hex($bytes);
	return sprintf(
		'%s-%s-%s-%s-%s',
		substr($hex, 0, 8),
		substr($hex, 8, 4),
		substr($hex, 12, 4),
		substr($hex, 16, 4),
		substr($hex, 20, 12)
	);
}

function combat_default_titler_json(string $name): string
{
	return json_encode([
		'@invis@' => $name,
		'Species:' => 'Test Duelist',
		'Mood:' => 'Focused',
		'Info:' => 'Autogenerated duel test character.',
		'Scent:' => 'None',
		'Currently:' => 'In testing mode.',
		'template' => 'character',
		'0' => $name,
	], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) ?: '{}';
}

function combat_default_stats_json(): string
{
	return json_encode([
		'health' => 20,
		'strength' => 10,
		'dexterity' => 10,
		'constitution' => 10,
		'magic' => 10,
		'class' => 0,
		'template' => 'stats',
	], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) ?: '{}';
}

function combat_default_options_json(): string
{
	return json_encode([
		'color' => '255,255,0',
		'opacity' => '1.0',
		'attach_point' => 'head',
		'position' => '<0,0,0>',
		'afk-ooc' => 0,
		'afk-msg' => '',
		'ooc-msg' => '',
		'template' => 'settings',
	], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) ?: '{}';
}

function combat_generate_test_name(): string
{
	$prefixes = ['Ari', 'Vex', 'Sora', 'Mira', 'Kael', 'Nox', 'Ilya', 'Tarin', 'Sel', 'Riven'];
	$suffixes = ['thorn', 'ash', 'vale', 'dusk', 'flare', 'warden', 'stride', 'ember', 'quill', 'bloom'];
	$titles = ['of Sand', 'of Storms', 'the Quiet', 'the Bold', 'the Grey', 'of Brass'];

	$base = $prefixes[random_int(0, count($prefixes) - 1)] . $suffixes[random_int(0, count($suffixes) - 1)];
	$title = $titles[random_int(0, count($titles) - 1)];
	return $base . ' ' . $title;
}

$playerUuid = combat_current_player_uuid();
if ($playerUuid === '') {
	combat_respond(401, ['ok' => false, 'error' => 'Not authenticated']);
}

$method = strtoupper($_SERVER['REQUEST_METHOD'] ?? 'GET');
$body = combat_get_json_body();
$action = (string)($_GET['action'] ?? $_POST['action'] ?? ($body['action'] ?? 'state'));
$action = trim($action);

try {
	$db = new DatabaseOperator();
	$db->connectToDatabase();
	$combat = new CombatService($db);
	$testMode = combat_is_test_mode($body);
	$effectivePlayerUuid = $playerUuid;
	$testActorUuid = combat_get_test_actor_uuid($body);

	if ($testMode && $testActorUuid !== null) {
		$known = $db->select(['player_uuid'], 'players', ['player_uuid'], [$testActorUuid]);
		if (count($known) === 0) {
			combat_respond(400, ['ok' => false, 'error' => 'Unknown test_actor_uuid']);
		}
		$effectivePlayerUuid = $testActorUuid;
	}

	if ($action === 'radar_sync' && ($method === 'POST')) {
		$radar = $body;
		if (count($radar) === 0) {
			$radar = $_POST;
		}
		$result = $combat->syncPresence($effectivePlayerUuid, is_array($radar) ? $radar : []);
		if ($testMode) {
			$result['acting_as_player_uuid'] = $effectivePlayerUuid;
		}
		combat_respond($result['ok'] ? 200 : 400, $result);
	}

	if ($action === 'test_sync_pair' && $method === 'POST') {
		if (!$testMode) {
			combat_respond(400, ['ok' => false, 'error' => 'test_mode=1 is required']);
		}
		$leftUuid = combat_normalize_uuid((string)($_POST['left_player_uuid'] ?? ($body['left_player_uuid'] ?? '')));
		$rightUuid = combat_normalize_uuid((string)($_POST['right_player_uuid'] ?? ($body['right_player_uuid'] ?? '')));
		if ($leftUuid === '' || $rightUuid === '') {
			combat_respond(400, ['ok' => false, 'error' => 'left_player_uuid and right_player_uuid are required']);
		}
		if ($leftUuid === $rightUuid) {
			combat_respond(400, ['ok' => false, 'error' => 'left_player_uuid and right_player_uuid must be different']);
		}

		$known = $db->select(['player_uuid'], 'players', ['player_uuid'], [$leftUuid]);
		if (count($known) === 0) {
			combat_respond(400, ['ok' => false, 'error' => 'Unknown left_player_uuid']);
		}
		$known = $db->select(['player_uuid'], 'players', ['player_uuid'], [$rightUuid]);
		if (count($known) === 0) {
			combat_respond(400, ['ok' => false, 'error' => 'Unknown right_player_uuid']);
		}

		$regionName = trim((string)($_POST['region_name'] ?? ($body['region_name'] ?? 'combat-test-lab')));
		$leftName = trim((string)($_POST['left_name'] ?? ($body['left_name'] ?? 'Left Tester')));
		$rightName = trim((string)($_POST['right_name'] ?? ($body['right_name'] ?? 'Right Tester')));

		$leftResult = $combat->syncPresence($leftUuid, [
			'region_name' => $regionName,
			'position' => ['x' => 128, 'y' => 128, 'z' => 20],
			'nearby' => [['player_uuid' => $rightUuid, 'name' => $rightName]],
		]);
		$rightResult = $combat->syncPresence($rightUuid, [
			'region_name' => $regionName,
			'position' => ['x' => 130, 'y' => 128, 'z' => 20],
			'nearby' => [['player_uuid' => $leftUuid, 'name' => $leftName]],
		]);

		$ok = (bool)($leftResult['ok'] ?? false) && (bool)($rightResult['ok'] ?? false);
		combat_respond($ok ? 200 : 400, [
			'ok' => $ok,
			'left' => $leftResult,
			'right' => $rightResult,
			'paired' => ['left_player_uuid' => $leftUuid, 'right_player_uuid' => $rightUuid, 'region_name' => $regionName],
		]);
	}

	if ($action === 'test_create_fake_pair' && $method === 'POST') {
		if (!$testMode) {
			combat_respond(400, ['ok' => false, 'error' => 'test_mode=1 is required']);
		}

		$leftName = trim((string)($_POST['left_name'] ?? ($body['left_name'] ?? '')));
		$rightName = trim((string)($_POST['right_name'] ?? ($body['right_name'] ?? '')));
		if ($leftName === '') {
			$leftName = combat_generate_test_name();
		}
		if ($rightName === '') {
			$rightName = combat_generate_test_name();
		}

		$leftPlayerUuid = combat_uuid_v4();
		$rightPlayerUuid = combat_uuid_v4();
		$createdStamp = date('m/d/Y g:i A');

		try {
			$db->beginTransaction();

			$db->insert(
				'players',
				['player_name', 'player_uuid', 'player_created', 'player_last_online', 'player_current_character', 'legacy_id'],
				[$leftName, $leftPlayerUuid, $createdStamp, $createdStamp, 0, 0]
			);
			$leftPlayerId = (int)$db->getPdo()->lastInsertId();
			$leftCharacterName = $leftName . ' (Test)';
			$db->insert(
				'player_characters',
				['player_id', 'character_name', 'character_titler', 'character_stats', 'character_options', 'legacy'],
				[$leftPlayerId, $leftCharacterName, combat_default_titler_json($leftCharacterName), combat_default_stats_json(), combat_default_options_json(), 0]
			);
			$leftCharacterId = (int)$db->getPdo()->lastInsertId();
			$db->update('players', ['player_current_character'], [$leftCharacterId], ['player_id'], [$leftPlayerId]);

			$db->insert(
				'players',
				['player_name', 'player_uuid', 'player_created', 'player_last_online', 'player_current_character', 'legacy_id'],
				[$rightName, $rightPlayerUuid, $createdStamp, $createdStamp, 0, 0]
			);
			$rightPlayerId = (int)$db->getPdo()->lastInsertId();
			$rightCharacterName = $rightName . ' (Test)';
			$db->insert(
				'player_characters',
				['player_id', 'character_name', 'character_titler', 'character_stats', 'character_options', 'legacy'],
				[$rightPlayerId, $rightCharacterName, combat_default_titler_json($rightCharacterName), combat_default_stats_json(), combat_default_options_json(), 0]
			);
			$rightCharacterId = (int)$db->getPdo()->lastInsertId();
			$db->update('players', ['player_current_character'], [$rightCharacterId], ['player_id'], [$rightPlayerId]);

			$db->commitTransaction();
		} catch (Throwable $e) {
			if ($db->inTransaction()) {
				$db->rollbackTransaction();
			}
			combat_respond(500, ['ok' => false, 'error' => 'Failed creating fake pair']);
		}

		combat_respond(200, [
			'ok' => true,
			'left' => [
				'player_id' => $leftPlayerId,
				'player_uuid' => $leftPlayerUuid,
				'player_name' => $leftName,
				'character_id' => $leftCharacterId,
				'character_name' => $leftCharacterName,
			],
			'right' => [
				'player_id' => $rightPlayerId,
				'player_uuid' => $rightPlayerUuid,
				'player_name' => $rightName,
				'character_id' => $rightCharacterId,
				'character_name' => $rightCharacterName,
			],
		]);
	}

	if ($action === 'targets' && $method === 'GET') {
		$result = $combat->listTargets($effectivePlayerUuid);
		if ($testMode) {
			$result['acting_as_player_uuid'] = $effectivePlayerUuid;
		}
		combat_respond(200, $result);
	}

	if ($action === 'pending_invites' && $method === 'GET') {
		$result = $combat->listPendingInvites($effectivePlayerUuid);
		if ($testMode) {
			$result['acting_as_player_uuid'] = $effectivePlayerUuid;
		}
		combat_respond(200, $result);
	}

	if ($action === 'challenge' && $method === 'POST') {
		$targetUuid = trim((string)($_POST['target_player_uuid'] ?? ($body['target_player_uuid'] ?? '')));
		if ($targetUuid === '') {
			combat_respond(400, ['ok' => false, 'error' => 'target_player_uuid is required']);
		}
		$turnSeconds = (int)($_POST['turn_seconds'] ?? ($body['turn_seconds'] ?? 90));
		$result = $combat->challenge($effectivePlayerUuid, $targetUuid, $turnSeconds);
		if ($testMode) {
			$result['acting_as_player_uuid'] = $effectivePlayerUuid;
		}
		combat_respond($result['ok'] ? 200 : 400, $result);
	}

	if ($action === 'join' && $method === 'POST') {
		$hostUuid = trim((string)($_POST['host_player_uuid'] ?? ($body['host_player_uuid'] ?? '')));
		$result = $combat->joinNearbyHost($effectivePlayerUuid, $hostUuid !== '' ? $hostUuid : null);
		if ($testMode) {
			$result['acting_as_player_uuid'] = $effectivePlayerUuid;
		}
		combat_respond($result['ok'] ? 200 : 400, $result);
	}

	if ($action === 'respond_invite' && $method === 'POST') {
		$instanceId = (int)($_POST['instance_id'] ?? ($body['instance_id'] ?? 0));
		if ($instanceId <= 0) {
			combat_respond(400, ['ok' => false, 'error' => 'instance_id is required']);
		}
		$acceptRaw = strtolower(trim((string)($_POST['accept'] ?? ($body['accept'] ?? '1'))));
		$accept = in_array($acceptRaw, ['1', 'true', 'yes', 'accept'], true);
		$result = $combat->respondToInvite($effectivePlayerUuid, $instanceId, $accept);
		if ($testMode) {
			$result['acting_as_player_uuid'] = $effectivePlayerUuid;
		}
		combat_respond($result['ok'] ? 200 : 400, $result);
	}

	if ($action === 'submit_action' && $method === 'POST') {
		$instanceId = (int)($_POST['instance_id'] ?? ($body['instance_id'] ?? 0));
		$actionType = trim((string)($_POST['action_type'] ?? ($body['action_type'] ?? 'wait')));
		$targetUuid = trim((string)($_POST['target_player_uuid'] ?? ($body['target_player_uuid'] ?? '')));
		$payload = $_POST['payload'] ?? ($body['payload'] ?? []);
		if (is_string($payload)) {
			$decoded = json_decode($payload, true);
			$payload = is_array($decoded) ? $decoded : [];
		}
		if (!is_array($payload)) {
			$payload = [];
		}

		if ($instanceId <= 0) {
			combat_respond(400, ['ok' => false, 'error' => 'instance_id is required']);
		}

		$result = $combat->submitAction($effectivePlayerUuid, $instanceId, $actionType, $targetUuid !== '' ? $targetUuid : null, $payload);
		if ($testMode) {
			$result['acting_as_player_uuid'] = $effectivePlayerUuid;
		}
		combat_respond($result['ok'] ? 200 : 400, $result);
	}

	if ($action === 'state' && $method === 'GET') {
		$instanceId = isset($_GET['instance_id']) ? (int)$_GET['instance_id'] : null;
		$result = $combat->getState($effectivePlayerUuid, $instanceId);
		if ($testMode) {
			$result['acting_as_player_uuid'] = $effectivePlayerUuid;
		}
		combat_respond(200, $result);
	}

	if ($action === 'tick' && ($method === 'POST' || $method === 'GET')) {
		$result = $combat->tick();
		combat_respond(200, $result);
	}

	combat_respond(400, ['ok' => false, 'error' => 'Unsupported action/method']);
} catch (Throwable $e) {
	themis_error_log('combat_api error: ' . $e->getMessage());
	combat_respond(500, ['ok' => false, 'error' => 'Internal error']);
}
